### PR TITLE
Added travic-ci compatibility.

### PR DESCRIPTION
**Pull request by boomboompower**
Changes:
- Config
- PlayerInteractEvent
+ PlayerAnimationEvent

### CODE REVIEW

**Comment by PluginIssueTrackingFRW** [comment]
Tried this, getting an issue for when player right clicks, making issue about it :P

**Comment by PluginIssueTrackingFTW** [comment]
Don't un-cancel an event once its already been cancelled unless you have a 110% legitimate reason.

**Comment by boomboompower** [comment]
@PluginIssueTrackingFTW im going to merge and squash this commit.

**Comment by PluginIssueTrackingFTW** [comment]
---------------
> Always register your events :stuck_out_tongue:

**Pull request merged**
